### ISSUE TITLE
React native New Architecture Support

### ISSUE THREAD

**Issue by BalajiGuruTSI** [kwkoo/dynatrace-react_native_plugin#2]
Hi 

Can anyone let me know from which version of **@dynatrace/react-native-plugin** supports React native New Architecture ?

Thanks in Advance.

**Comment by BalajiGuruTSI** [comment]
> Hi
> 
> Can anyone let me know from which version of **@dynatrace/react-native-plugin** supports React native New Architecture ?
> 
> Thanks in Advance.

we are using **@dynatrace/react-native-plugin v2.277.1** .  Does it supports new arch ?

**Comment by TheHighriser** [comment]
First of all. This is not an official repository. Questions like this can be asked via support and will be answered. Did you try the latest version available already (2.283)? As the new architecture is still experimental we didn't mention it yet in our changelog but 283 contains already partial support for it.

**Comment by harp79** [comment]
To the owner of this repo @kwkoo 
could you please archive this and/or set it to private as this is no longer active and not the official Dynatrace ReactNative plugin. We would like to avoid confusing it with the official ReactNative Plugin maintained by Dynatrace.
Thank You!

**Comment by kwkoo** [comment]
>  please archive this and/or set it to private as this is no longer active and not the official Dynatrace ReactNative plugin

Thank you for the suggestion. I will archive this repo.
